name: GuildasFM
author: [FullEDITByRqsner]
description: Plugin de Guilda
version: 0.1#Beta
main: FactionsPro\FactionMain
api:
- 1.14.0
- 2.0.0
commands:
  guilda:
    description: use /guilda ajuda para Listar os Comandos De Guilda
    permission: f.command
  g:
    description: use /g ajuda Para Listar os Comandos de Guilda
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Permite Usar todos os Comandos de Guilda"
